### ISSUE TITLE
Error when installing required dependencies

### ISSUE THREAD

**Issue by drmurdock** [ldingemans/PhenoScore#12]
Hi, I'm having difficulty installing PhenoScore on Ubuntu 22.04.3 using the provided instructions. The issue occurs when installing dependencies after creating a new conda environment as instructed:

pip install -r requirements.txt

This will run for a while but then gets hung up and fails at this spot:

Collecting lightgbm (from phenopy@ git+https://github.com/GeneDx/phenopy.git@1709c8c676f215ad71772da5e5d4da240c3ec82d->-r requirements.txt (line 6))
  Using cached lightgbm-4.2.0-py3-none-manylinux_2_28_x86_64.whl.metadata (19 kB)
  Using cached lightgbm-4.1.0-py3-none-manylinux_2_28_x86_64.whl.metadata (19 kB)
  Using cached lightgbm-4.0.0-py3-none-manylinux_2_28_x86_64.whl.metadata (19 kB)
  Using cached lightgbm-3.3.5-py3-none-manylinux1_x86_64.whl.metadata (15 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/home/dmurdock/anaconda3/envs/PhenoScore/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/dmurdock/anaconda3/envs/PhenoScore/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/home/dmurdock/anaconda3/envs/PhenoScore/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/home/dmurdock/anaconda3/envs/PhenoScore/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/home/dmurdock/anaconda3/envs/PhenoScore/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/dmurdock/anaconda3/envs/PhenoScore/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000

Any idea what the issue could be? Also, assuming I get this working, at what step do I install cuDNN?

Thanks,
David

**Comment by ldingemans** [comment]
Hey @drmurdock thanks for your interest in PhenoScore. Could you try to install the ``develop`` branch? I have been trying to make the package more lean because of this dependency hell that has developed lately. 

See the instructions in the readme of develop:

To install PhenoScore using conda, it is advisable (but not strictly necessary) to create a new environment first:

conda create -n PhenoScore python=3.9

Then, activate the environment

conda activate PhenoScore

Install PhenoScore and the needed dependencies:

pip install .

To fix some dependency issues, especially on Windows, please then run these commands:

pip install mxnet==1.7.0post2 --no-dependencies

pip install numpy==1.23.5


After all this, you can install cuDNN with

``conda install cudnn``

let me know if this works, or if you run into other issues I can help you with

**Comment by drmurdock** [comment]
Thank you @ldingemans! The only additional thing I had to do was:

pip install graphviz==0.8.1

After this, everything is working just fine. This is a very impressive work. Thank you for sharing it. I may contact you directly to discuss additional applications of this tool.

Best,
David
